import { createSalePayment, type SaleInitialPaymentInput } from "@/services/sales";

function decimalSignature(value: string): string {
  // Preserve exact cents, including exponent notation, without using Number.
  const match = /^([+-]?)(\d*)(?:\.(\d*))?(?:e([+-]?\d+))?$/i.exec(value.trim());
  if (!match || !(match[2] || match[3])) return value;
  const digits = `${match[2]}${match[3] ?? ""}`.replace(/^0+/, "");
  if (!digits) return "0";
  const coefficient = digits.replace(/0+$/, "");
  const exponent = BigInt(match[4] ?? "0") - BigInt((match[3] ?? "").length) + BigInt(digits.length - coefficient.length);
  return `${match[1] === "-" ? "-" : ""}${coefficient}e${exponent}`;
}

function signature(saleId: string, payload: SaleInitialPaymentInput): string {
  return JSON.stringify([
    saleId, payload.payment_method_id, decimalSignature(payload.amount_ars), payload.received_at ?? null,
    payload.reference?.trim() || null, payload.notes?.trim() || null,
  ]);
}

/** One modal's payment intention. Keys are generated by events, never rendering. */
export function createSalePaymentIntent(makeKey = () => crypto.randomUUID()) {
  return createPaymentIntent(createSalePayment, makeKey);
}

type PaymentSender<T> = (saleId: string, payload: T, key: string) => Promise<unknown>;

/** Shared by individual payments and confirmation with an initial payment. */
export function createPaymentIntent<T extends SaleInitialPaymentInput>(sendPayment: PaymentSender<T>, makeKey = () => crypto.randomUUID()) {
  return createRequestIntent(sendPayment, makeKey, signature);
}

/** Keep the key across failures; edits invalidate it without generating UUIDs.
 * The next valid submission allocates the new key. Pending requests are frozen.
 */
export function createRequestIntent<T>(sendPayment: PaymentSender<T>, makeKey: () => string, getSignature: (saleId: string, payload: T) => string) {
  let key: string | null = null;
  let previousSignature: string | null = null;
  let pending = false;
  let completed = false;
  return {
    get pending() { return pending; },
    invalidate() {
      if (pending || completed) return false;
      key = null;
      previousSignature = null;
      return true;
    },
    begin() {
      if (pending) return false;
      key = makeKey();
      previousSignature = null;
      completed = false;
      return true;
    },
    async submit(saleId: string, payload: T, send = sendPayment) {
      if (pending || completed) return false;
      const currentSignature = getSignature(saleId, payload);
      if (key === null || (previousSignature !== null && previousSignature !== currentSignature)) key = makeKey();
      previousSignature = currentSignature;
      pending = true;
      try {
        await send(saleId, payload, key);
        completed = true;
        key = null;
        previousSignature = null;
        return true;
      } finally {
        // Failures preserve the key and signature for an unchanged retry.
        pending = false;
      }
    },
  };
}
