import { createSalePayment, type SalePaymentInput } from "@/services/sales";

function decimalSignature(value: string): string {
  // Preserve exact cents, including exponent notation, without using Number.
  const match = /^([+-]?)(\d*)(?:\.(\d*))?(?:e([+-]?\d+))?$/i.exec(value.trim());
  if (!match || !(match[2] || match[3])) return value;
  const digits = `${match[2]}${match[3] ?? ""}`.replace(/^0+/, "");
  if (!digits) return "0";
  const coefficient = digits.replace(/0+$/, "");
  const exponent = BigInt(match[4] ?? "0") - BigInt((match[3] ?? "").length) + BigInt(digits.length - coefficient.length);
  return `${match[1] === "-" ? "-" : ""}${coefficient}e${exponent}`;
}

function signature(saleId: string, payload: SalePaymentInput): string {
  return JSON.stringify([
    saleId, payload.payment_method_id, decimalSignature(payload.amount_ars), payload.received_at,
    payload.reference?.trim() || null, payload.notes?.trim() || null,
  ]);
}

/** One modal's payment intention. Keys are generated by events, never rendering. */
export function createSalePaymentIntent(makeKey = () => crypto.randomUUID()) {
  let key: string | null = null;
  let previousSignature: string | null = null;
  let pending = false;
  let completed = false;
  return {
    get pending() { return pending; },
    begin() {
      if (pending) return false;
      key = makeKey();
      previousSignature = null;
      completed = false;
      return true;
    },
    async submit(saleId: string, payload: SalePaymentInput, send = createSalePayment) {
      if (pending || completed) return false;
      const currentSignature = signature(saleId, payload);
      if (key === null || (previousSignature !== null && previousSignature !== currentSignature)) key = makeKey();
      previousSignature = currentSignature;
      pending = true;
      try {
        await send(saleId, payload, key);
        completed = true;
        return true;
      } finally {
        // Failures preserve the key and signature for an unchanged retry.
        pending = false;
      }
    },
  };
}
