"use client";

import { ChevronDown, Plus, Search, ShoppingBag, SlidersHorizontal } from "lucide-react";
import Link from "next/link";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

import { formatPurchaseCurrency, formatPurchaseDate } from "@/features/purchases/components/purchase-helpers";
import { labelSaleStatus } from "@/features/sales/components/sale-helpers";
import { getApiErrorMessage } from "@/lib/api";
import { getOwners } from "@/services/owners";
import { getPatients } from "@/services/patients";
import { getSaleFilterOptions, getSales } from "@/services/sales";
import type { Owner, Patient, PurchaseCreatorOption, SaleListFilters, SaleSummary } from "@/types/api";

export function SalesScreen() {
  const router = useRouter(); const pathname = usePathname(); const searchParams = useSearchParams(); const queryString = searchParams.toString();
  const filters = useMemo(() => readFilters(queryString), [queryString]);
  const [search, setSearch] = useState(filters.search ?? ""); const [items, setItems] = useState<SaleSummary[]>([]);
  const [owners, setOwners] = useState<Owner[]>([]); const [patients, setPatients] = useState<Patient[]>([]); const [creators, setCreators] = useState<PurchaseCreatorOption[]>([]);
  const [meta, setMeta] = useState({ page: 1, page_size: 20, total: 0, total_pages: 0 }); const [isLoading, setIsLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const [isFiltersOpen, setIsFiltersOpen] = useState(false); const activeCount = countAdvanced(filters);
  useEffect(() => setSearch(filters.search ?? ""), [filters.search]);
  const load = useCallback(async () => { setIsLoading(true); setError(null); try { const response = await getSales(filters); setItems(response.data); setMeta(response.meta); } catch (value) { setError(getApiErrorMessage(value)); } finally { setIsLoading(false); } }, [filters]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { Promise.all([getOwners({ page: 1, pageSize: 100 }), getPatients({ page: 1, pageSize: 100 }), getSaleFilterOptions()]).then(([ownerResponse, patientResponse, options]) => { setOwners(ownerResponse.data); setPatients(patientResponse.data); setCreators(options.data.creators); }).catch(() => {}); }, []);

  function update(updates: Record<string, string | number | null>) { const params = new URLSearchParams(queryString); Object.entries(updates).forEach(([key, value]) => { if (value === null || value === "") params.delete(key); else params.set(key, String(value)); }); if (!("page" in updates)) params.delete("page"); router.push(`${pathname}${params.toString() ? `?${params}` : ""}`, { scroll: false }); }
  function submit(event: FormEvent) { event.preventDefault(); update({ search: search.trim() || null }); }
  function clear() { setSearch(""); setIsFiltersOpen(false); router.push(pathname, { scroll: false }); }
  const hasFilters = Boolean(filters.search || activeCount);

  return <div className="page-stack sales-page">
    <section className="screen-heading list-page__header"><div><p className="eyebrow">Operaciones</p><h1>Ventas</h1><p>Registra borradores y confirma ventas con trazabilidad de inventario.</p></div><Link className="primary-button" href="/sales/new"><Plus size={18} /> Nueva venta</Link></section>
    <section className="panel purchase-filter-toolbar" aria-label="Búsqueda y filtros de ventas"><form className="purchase-search" onSubmit={submit}><label className="field"><span>Buscar</span><input placeholder="Cliente, paciente, producto o servicio" value={search} onChange={(event) => setSearch(event.target.value)} /></label><button className="secondary-button" type="submit"><Search size={17} /> Buscar</button></form><button aria-controls="sale-advanced-filters" aria-expanded={isFiltersOpen} className="secondary-button purchase-filters-toggle" type="button" onClick={() => setIsFiltersOpen((current) => !current)}><SlidersHorizontal size={17} /> Filtros{activeCount ? ` (${activeCount})` : ""}<ChevronDown size={16} /></button></section>
    {isFiltersOpen ? <section id="sale-advanced-filters" className="panel purchase-filters" aria-label="Filtros avanzados de ventas">
      <label className="field"><span>Propietario</span><select value={filters.owner_id ?? ""} onChange={(event) => update({ owner_id: event.target.value || null, patient_id: null })}><option value="">Todos</option>{owners.map((owner) => <option key={owner.id} value={owner.id}>{owner.full_name}</option>)}</select></label>
      <label className="field"><span>Paciente</span><select value={filters.patient_id ?? ""} onChange={(event) => update({ patient_id: event.target.value || null })}><option value="">Todos</option>{patients.filter((patient) => !filters.owner_id || patient.owner_id === filters.owner_id).map((patient) => <option key={patient.id} value={patient.id}>{patient.name}</option>)}</select></label>
      <label className="field"><span>Estado</span><select value={filters.status ?? ""} onChange={(event) => update({ status: event.target.value || null })}><option value="">Todos</option><option value="draft">Borrador</option><option value="confirmed">Confirmada</option><option value="cancelled">Cancelada</option><option value="reversed">Revertida</option></select></label>
      <label className="field"><span>Tipo de línea</span><select value={filters.line_type ?? ""} onChange={(event) => update({ line_type: event.target.value || null })}><option value="">Todos</option><option value="product">Producto</option><option value="service">Servicio</option></select></label>
      <label className="field"><span>Desde</span><input type="date" value={filters.date_from ?? ""} onChange={(event) => update({ date_from: event.target.value || null })} /></label><label className="field"><span>Hasta</span><input type="date" value={filters.date_to ?? ""} onChange={(event) => update({ date_to: event.target.value || null })} /></label>
      <label className="field"><span>Usuario</span><select value={filters.created_by_user_id ?? ""} onChange={(event) => update({ created_by_user_id: event.target.value || null })}><option value="">Todos</option>{creators.map((creator) => <option key={creator.id} value={creator.id}>{creator.full_name}</option>)}</select></label>
      <label className="field"><span>Ordenar</span><select value={filters.sort_by ?? "sale_date"} onChange={(event) => update({ sort_by: event.target.value })}><option value="sale_date">Fecha</option><option value="created_at">Registro</option><option value="total_ars">Total</option><option value="status">Estado</option></select></label>
      <label className="field"><span>Dirección</span><select value={filters.sort_direction ?? "desc"} onChange={(event) => update({ sort_direction: event.target.value })}><option value="desc">Descendente</option><option value="asc">Ascendente</option></select></label>
      <label className="field"><span>Por página</span><select value={filters.page_size ?? 20} onChange={(event) => update({ page_size: Number(event.target.value) })}><option value="10">10</option><option value="20">20</option><option value="50">50</option><option value="100">100</option></select></label>{hasFilters ? <button className="secondary-button purchase-filters__clear" type="button" onClick={clear}>Limpiar filtros</button> : null}
    </section> : null}
    {error ? <section className="error-state" role="alert">{error}</section> : null}{isLoading ? <div className="loading-card" aria-label="Cargando ventas" /> : null}
    {!isLoading && !error && !items.length ? <section className="empty-state"><ShoppingBag size={30} /><h2>{hasFilters ? "No hay ventas para estos filtros" : "Todavía no hay ventas"}</h2><p>{hasFilters ? "Ajusta o limpia los filtros." : "Crea el primer borrador de venta."}</p>{!hasFilters ? <Link className="primary-button" href="/sales/new">Nueva venta</Link> : null}</section> : null}
    {!isLoading && items.length ? <><section className="inventory-table-card" aria-label="Listado de ventas"><div className="inventory-table-scroll"><table className="inventory-table sale-table"><thead><tr><th>Fecha</th><th>Cliente</th><th>Paciente</th><th>Líneas</th><th>Subtotal</th><th>Descuentos</th><th>Total</th><th>Estado</th><th>Usuario</th></tr></thead><tbody>{items.map((sale) => <tr key={sale.id} className="inventory-table__row--clickable" role="link" tabIndex={0} onClick={() => router.push(`/sales/${sale.id}`)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); router.push(`/sales/${sale.id}`); } }}><td>{formatPurchaseDate(sale.sale_date)}</td><td className="sale-text"><strong>{sale.owner_name_snapshot || "Venta de mostrador"}</strong></td><td className="sale-text">{sale.patient_name_snapshot || "—"}</td><td>{sale.item_count}</td><td className="sale-money">{formatPurchaseCurrency(sale.subtotal_ars)}</td><td className="sale-money">{formatPurchaseCurrency(sale.discount_total_ars)}</td><td className="sale-money"><strong>{formatPurchaseCurrency(sale.total_ars)}</strong></td><td><span className={`badge sale-status sale-status--${sale.status}`}>{labelSaleStatus(sale.status)}</span></td><td className="sale-text"><strong>{sale.created_by_user_name || sale.created_by_user_email || "Sin usuario registrado"}</strong></td></tr>)}</tbody></table></div></section><nav className="purchase-pagination" aria-label="Paginación de ventas"><button className="secondary-button" disabled={meta.page <= 1} onClick={() => update({ page: meta.page - 1 })}>Anterior</button><span>Página {meta.page} de {Math.max(meta.total_pages, 1)} · {meta.total} ventas</span><button className="secondary-button" disabled={meta.page >= meta.total_pages} onClick={() => update({ page: meta.page + 1 })}>Siguiente</button></nav></> : null}
  </div>;
}

function readFilters(query: string): SaleListFilters { const params = new URLSearchParams(query); const status = params.get("status"); const lineType = params.get("line_type"); const pageSize = Number(params.get("page_size")); const sort = params.get("sort_by"); return { search: params.get("search") || undefined, owner_id: params.get("owner_id") || undefined, patient_id: params.get("patient_id") || undefined, status: status === "draft" || status === "confirmed" || status === "cancelled" || status === "reversed" ? status : undefined, line_type: lineType === "product" || lineType === "service" ? lineType : undefined, date_from: params.get("date_from") || undefined, date_to: params.get("date_to") || undefined, created_by_user_id: params.get("created_by_user_id") || undefined, page: Math.max(1, Number(params.get("page")) || 1), page_size: [10, 20, 50, 100].includes(pageSize) ? pageSize : 20, sort_by: ["sale_date", "created_at", "total_ars", "status"].includes(sort ?? "") ? sort as SaleListFilters["sort_by"] : "sale_date", sort_direction: params.get("sort_direction") === "asc" ? "asc" : "desc" }; }
function countAdvanced(filters: SaleListFilters) { return [filters.owner_id, filters.patient_id, filters.status, filters.line_type, filters.date_from || filters.date_to, filters.created_by_user_id].filter(Boolean).length; }
