"""add timezone to tenants"""

revision = '0018_add_timezone_to_tenants'
down_revision = '0017_consult_med_inventory'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tenants",
        sa.Column(
            "timezone",
            sa.String(64),
            nullable=False,
            server_default="America/Panama",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tenants", "timezone")
    # ### end Alembic commands ###
