services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: vetflow
      POSTGRES_PASSWORD: vetflow
      POSTGRES_DB: vetflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_vetflow_data:/var/lib/postgresql/data

volumes:
  postgres_vetflow_data:
